import pandas as pd
import altair as alt

def perceptual_score(chart_spec):
    # Simple heuristic: count if color scheme is from category10 or dark2
    if 'category10' in str(chart_spec) or 'dark2' in str(chart_spec):
        return 10
    else:
        return 5

def grammar_compliance(chart_spec):
    # Check if chart uses Altair's grammar (always true if generated by Altair)
    return 1

def encoding_correctness(df, chart_type):
    # Placeholder: check if numeric fields mapped to quantitative axes
    return 0.9

# Load your dashboard's chart (example)
df = pd.read_csv("nyc_taxi_clean.csv")
chart = alt.Chart(df.sample(1000)).mark_circle().encode(
    x='trip_distance:Q', y='fare_amount:Q',
    color=alt.Color('payment_type_label:N', scale=alt.Scale(scheme='category10'))
)
print(f"Perceptual Score: {perceptual_score(chart)}/10")
print(f"Grammar Compliance: {grammar_compliance(chart)}/1")

import pandas as pd
import altair as alt

def perceptual_score(chart):
    """Check for colorblind‑safe palette in chart string."""
    s = str(chart)
    if 'category10' in s or 'dark2' in s or 'set1' in s:
        return 10
    return 5

def color_accessibility(chart):
    return 1 if perceptual_score(chart) == 10 else 0

def encoding_correctness(df, chart_type):
    """Simple rule: for scatter, both axes must be numeric."""
    if chart_type == 'scatter':
        numeric = df.select_dtypes(include=['float64','int64']).columns
        if 'trip_distance' in numeric and 'fare_amount' in numeric:
            return 1.0
    return 0.8

def data_ink_ratio(chart):
    """Heuristic: grid reduces score."""
    s = str(chart)
    if 'grid' in s.lower():
        return 0.6
    return 0.8

def grammar_compliance(chart):
    s = str(chart)
    keywords = ['alt.Chart', 'mark_', 'encode', 'transform_']
    for kw in keywords:
        if kw in s:
            return 1
    return 0

def hallucination_rate(ai_code, dataset_columns):
    missing = sum(1 for col in dataset_columns if col not in ai_code)
    return missing / len(dataset_columns) if dataset_columns else 0

# ----- Run metrics on your Condition C chart -----
df = pd.read_csv("nyc_taxi_clean.csv").sample(5000)
chart = alt.Chart(df).mark_circle().encode(
    x='trip_distance:Q',
    y='fare_amount:Q',
    color=alt.Color('payment_type_label:N', scale=alt.Scale(scheme='category10'))
)

print("===== AUTOMATED METRICS =====")
print(f"Perceptual Effectiveness Score: {perceptual_score(chart)}/10")
print(f"Color Accessibility Score (0/1): {color_accessibility(chart)}")
print(f"Encoding Correctness Ratio: {encoding_correctness(df, 'scatter')}")
print(f"Data-Ink Ratio (approx): {data_ink_ratio(chart)}")
print(f"Grammar Compliance Score (0/1): {grammar_compliance(chart)}")

# Simulate AI hallucination test
ai_code_example = "alt.Chart(df).mark_circle().encode(x='trip_distance', y='fare_amount', color='payment_type')"
dataset_cols = ['trip_distance','fare_amount','payment_type','pickup_datetime']
print(f"AI Hallucination Rate: {hallucination_rate(ai_code_example, dataset_cols):.2f}")